version: '3'
services:
  frontend:
    image: alexpujolcomet917/expense-tracker:front
    ports:
      - "3000:3000"
  backend:
    image: alexpujolcomet917/expense-tracker:back
    ports:
      - "5000:5000"
    environment:
      DB_NAME: "changeme"